# Generated by Django 3.0.3 on 2020-04-24 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeTitle', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RoomType_Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Facility')),
                ('roomType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.RoomType')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('size', models.IntegerField()),
                ('photos', models.ImageField(upload_to='RoomPhotos')),
                ('roomType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.RoomType')),
            ],
        ),
    ]
