# Generated by Django 3.0.3 on 2020-04-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='availableStatus',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('UNDER MAINTENANCE', 'Under Maintenance')], default='AVAILABLE', max_length=17),
        ),
    ]
