# Generated by Django 3.0.3 on 2020-04-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_booking_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approve',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
