# Generated by Django 3.0.3 on 2020-04-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20200428_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approve',
            name='result',
            field=models.CharField(choices=[('APPROVED', 'approve'), ('DISAPPROVED', 'approve'), ('PENDING', 'pending')], max_length=11),
        ),
    ]
